spring.application.name=Bookora

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://bookora-db.c9ygacg2o7ak.ap-south-2.rds.amazonaws.com:3306/bookora
spring.datasource.username=bookora_admin
spring.datasource.password=${DB_PASSWORD}

jwt.secret=BookoraJwtSecretKeyForSpringawsSecurity1234567890
jwt.expiration-ms=86400000
